// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Nine.Infrastructure.Data;
using Nine.Infrastructure.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
